# Form implementation generated from reading ui file 'college_form.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QFont


class Ui_AddCollege_Window(object):
    def setupUi(self, AddCollege_Window):
        AddCollege_Window.setObjectName("AddCollege_Window")
        AddCollege_Window.resize(454, 320)
        self.centralwidget = QtWidgets.QWidget(parent=AddCollege_Window)
        self.centralwidget.setStyleSheet("*{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"}\n"
"#centralwidget{\n"
"    background-color: #073b4c;\n"
"}\n"
"#frame_3, #frame_5{\n"
"    padding: 10px;\n"
"    background-color: #073b4c;\n"
"    border-radius: 10px;\n"
"}\n"
"#frame_4{\n"
"    padding: 10px;\n"
"    background-color: #06d6a0;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton{\n"
"    padding: 5px;\n"
"    background-color: #118ab2;\n"
"    border-radius: 5px;\n"
"}\n"
"QLineEdit {\n"
"    color: black;\n"
"    padding: 3px;\n"
"    background-color: rgba(255, 255, 255, 0.6);\n"
"    border-radius: 5px;\n"
"}\n"
"#label{\n"
"    color: #073b4c;\n"
"}\n"
"")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout_14 = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout_14.setObjectName("gridLayout_14")
        self.frame_3 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_3.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_3.setObjectName("frame_3")
        self.gridLayout_15 = QtWidgets.QGridLayout(self.frame_3)
        self.gridLayout_15.setObjectName("gridLayout_15")
        self.frame_4 = QtWidgets.QFrame(parent=self.frame_3)
        self.frame_4.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_4.setObjectName("frame_4")
        self.gridLayout_13 = QtWidgets.QGridLayout(self.frame_4)
        self.gridLayout_13.setObjectName("gridLayout_13")
        self.frame_5 = QtWidgets.QFrame(parent=self.frame_4)
        self.frame_5.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_5.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_5.setObjectName("frame_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.frame_5)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.college_name = QtWidgets.QLabel(parent=self.frame_5)
        font = QtGui.QFont()
        font = QFont("Montserrat")
        font.setWeight(QFont.Weight.Bold)
        self.college_name.setFont(font)
        self.college_name.setObjectName("college_name")
        self.verticalLayout_2.addWidget(self.college_name)
        self.cname_info = QtWidgets.QLineEdit(parent=self.frame_5)
        font = QtGui.QFont()
        font = QFont("Montserrat")
        font.setWeight(QFont.Weight.DemiBold)
        self.cname_info.setFont(font)
        self.cname_info.setObjectName("cname_info")
        self.verticalLayout_2.addWidget(self.cname_info)
        self.college_code = QtWidgets.QLabel(parent=self.frame_5)
        font = QtGui.QFont()
        font = QFont("Montserrat")
        font.setWeight(QFont.Weight.Bold)
        self.college_code.setFont(font)
        self.college_code.setObjectName("college_code")
        self.verticalLayout_2.addWidget(self.college_code)
        self.ccode_info = QtWidgets.QLineEdit(parent=self.frame_5)
        font = QtGui.QFont()
        font = QFont("Montserrat")
        font.setWeight(QFont.Weight.DemiBold)
        self.ccode_info.setFont(font)
        self.ccode_info.setObjectName("ccode_info")
        self.verticalLayout_2.addWidget(self.ccode_info)
        self.gridLayout_13.addWidget(self.frame_5, 1, 0, 1, 3)
        self.ccancel_btn = QtWidgets.QPushButton(parent=self.frame_4)
        font = QtGui.QFont()
        font = QFont("Montserrat")
        font.setWeight(QFont.Weight.DemiBold)
        self.ccancel_btn.setFont(font)
        self.ccancel_btn.setObjectName("ccancel_btn")
        self.gridLayout_13.addWidget(self.ccancel_btn, 2, 2, 1, 1)
        self.cadd_btn = QtWidgets.QPushButton(parent=self.frame_4)
        font = QtGui.QFont()
        font = QFont("Montserrat")
        font.setWeight(QFont.Weight.DemiBold)
        self.cadd_btn.setFont(font)
        self.cadd_btn.setObjectName("cadd_btn")
        self.gridLayout_13.addWidget(self.cadd_btn, 2, 0, 1, 1)
        self.cclear_btn = QtWidgets.QPushButton(parent=self.frame_4)
        font = QtGui.QFont()
        font = QFont("Montserrat")
        font.setWeight(QFont.Weight.DemiBold)
        self.cclear_btn.setFont(font)
        self.cclear_btn.setObjectName("cclear_btn")
        self.gridLayout_13.addWidget(self.cclear_btn, 2, 1, 1, 1)
        self.label = QtWidgets.QLabel(parent=self.frame_4)
        font = QtGui.QFont()
        font = QFont("Montserrat")
        font.setWeight(QFont.Weight.Black)
        font.setPointSize(9)
        # font.setBold(True)
        # font.setWeight(75)
        self.label.setFont(font)
        self.label.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_13.addWidget(self.label, 0, 1, 1, 1)
        self.gridLayout_15.addWidget(self.frame_4, 0, 0, 1, 1)
        self.gridLayout_14.addWidget(self.frame_3, 0, 0, 1, 1)
        AddCollege_Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(AddCollege_Window)
        QtCore.QMetaObject.connectSlotsByName(AddCollege_Window)

    def retranslateUi(self, AddCollege_Window):
        _translate = QtCore.QCoreApplication.translate
        AddCollege_Window.setWindowTitle(_translate("AddCollege_Window", "MainWindow"))
        self.college_name.setText(_translate("AddCollege_Window", "Name"))
        self.college_code.setText(_translate("AddCollege_Window", "Code"))
        self.ccancel_btn.setText(_translate("AddCollege_Window", "Cancel"))
        self.cadd_btn.setText(_translate("AddCollege_Window", "Add"))
        self.cclear_btn.setText(_translate("AddCollege_Window", "Clear"))
        self.label.setText(_translate("AddCollege_Window", "ADD COLLEGE"))
