# Form implementation generated from reading ui file 'program_form.ui'
#
# Created by: PyQt6 UI code generator 6.9.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from PyQt6.QtGui import QFont


class Ui_AddProgram_Window(object):
    def setupUi(self, AddProgram_Window):
        AddProgram_Window.setObjectName("AddProgram_Window")
        AddProgram_Window.resize(439, 321)
        self.centralwidget = QtWidgets.QWidget(parent=AddProgram_Window)
        self.centralwidget.setStyleSheet("*{\n"
"    border: none;\n"
"    background-color: transparent;\n"
"    color: #fff;\n"
"}\n"
"#centralwidget{\n"
"    background-color: #073b4c;\n"
"}\n"
"#frame_21, #frame_23{\n"
"    padding: 10px;\n"
"    background-color: #073b4c;\n"
"    border-radius: 10px;\n"
"}\n"
"#frame_22{\n"
"    padding: 10px;\n"
"    background-color: #06d6a0;\n"
"    border-radius: 10px;\n"
"}\n"
"QPushButton{\n"
"    padding: 5px;\n"
"    background-color: #118ab2;\n"
"    border-radius: 5px;\n"
"}\n"
"QLineEdit, QComboBox {\n"
"    color: black;\n"
"    padding: 3px;\n"
"    background-color: rgba(255, 255, 255, 0.6);\n"
"    border-radius: 5px;\n"
"}\n"
"QComboBox QAbstractItemView {\n"
"    background-color: black;\n"
"    color: white;\n"
"    selection-background-color: #555555;\n"
"    selection-color: white;\n"
"}\n"
"#plabel{\n"
"    color: #073b4c;\n"
"}")
        self.centralwidget.setObjectName("centralwidget")
        self.gridLayout = QtWidgets.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName("gridLayout")
        self.frame_21 = QtWidgets.QFrame(parent=self.centralwidget)
        self.frame_21.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_21.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_21.setObjectName("frame_21")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.frame_21)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.frame_22 = QtWidgets.QFrame(parent=self.frame_21)
        self.frame_22.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_22.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_22.setObjectName("frame_22")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.frame_22)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.plabel = QtWidgets.QLabel(parent=self.frame_22)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setWeight(QFont.Weight.Black)
        font.setPointSize(9)
        # font.setBold(True)
        # font.setWeight(75)
        self.plabel.setFont(font)
        self.plabel.setAlignment(QtCore.Qt.AlignmentFlag.AlignCenter)
        self.plabel.setObjectName("plabel")
        self.gridLayout_3.addWidget(self.plabel, 0, 1, 1, 1)
        self.frame_23 = QtWidgets.QFrame(parent=self.frame_22)
        self.frame_23.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.frame_23.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.frame_23.setObjectName("frame_23")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.frame_23)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.prog_college = QtWidgets.QLabel(parent=self.frame_23)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setWeight(QFont.Weight.Bold)
        self.prog_college.setFont(font)
        self.prog_college.setObjectName("prog_college")
        self.verticalLayout.addWidget(self.prog_college)
        self.pcollege_info = QtWidgets.QComboBox(parent=self.frame_23)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setWeight(QFont.Weight.DemiBold)
        self.pcollege_info.setFont(font)
        self.pcollege_info.setObjectName("pcollege_info")
        self.verticalLayout.addWidget(self.pcollege_info)
        self.prog_name = QtWidgets.QLabel(parent=self.frame_23)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setWeight(QFont.Weight.Bold)
        self.prog_name.setFont(font)
        self.prog_name.setObjectName("prog_name")
        self.verticalLayout.addWidget(self.prog_name)
        self.pname_info = QtWidgets.QLineEdit(parent=self.frame_23)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setWeight(QFont.Weight.DemiBold)
        self.pname_info.setFont(font)
        self.pname_info.setObjectName("pname_info")
        self.verticalLayout.addWidget(self.pname_info)
        self.prog_code = QtWidgets.QLabel(parent=self.frame_23)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setWeight(QFont.Weight.Bold)
        self.prog_code.setFont(font)
        self.prog_code.setObjectName("prog_code")
        self.verticalLayout.addWidget(self.prog_code)
        self.pcode_info = QtWidgets.QLineEdit(parent=self.frame_23)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setWeight(QFont.Weight.DemiBold)
        self.pcode_info.setFont(font)
        self.pcode_info.setObjectName("pcode_info")
        self.verticalLayout.addWidget(self.pcode_info)
        self.gridLayout_3.addWidget(self.frame_23, 1, 0, 1, 3)
        self.padd_btn = QtWidgets.QPushButton(parent=self.frame_22)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setWeight(QFont.Weight.DemiBold)
        self.padd_btn.setFont(font)
        self.padd_btn.setObjectName("padd_btn")
        self.gridLayout_3.addWidget(self.padd_btn, 2, 0, 1, 1)
        self.pclear_btn = QtWidgets.QPushButton(parent=self.frame_22)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setWeight(QFont.Weight.DemiBold)
        self.pclear_btn.setFont(font)
        self.pclear_btn.setObjectName("pclear_btn")
        self.gridLayout_3.addWidget(self.pclear_btn, 2, 1, 1, 1)
        self.pcancel_btn = QtWidgets.QPushButton(parent=self.frame_22)
        font = QtGui.QFont()
        font.setFamily("Montserrat")
        font.setWeight(QFont.Weight.DemiBold)
        self.pcancel_btn.setFont(font)
        self.pcancel_btn.setObjectName("pcancel_btn")
        self.gridLayout_3.addWidget(self.pcancel_btn, 2, 2, 1, 1)
        self.gridLayout_2.addWidget(self.frame_22, 0, 0, 1, 1)
        self.gridLayout.addWidget(self.frame_21, 0, 0, 1, 1)
        AddProgram_Window.setCentralWidget(self.centralwidget)

        self.retranslateUi(AddProgram_Window)
        QtCore.QMetaObject.connectSlotsByName(AddProgram_Window)

    def retranslateUi(self, AddProgram_Window):
        _translate = QtCore.QCoreApplication.translate
        AddProgram_Window.setWindowTitle(_translate("AddProgram_Window", "MainWindow"))
        self.plabel.setText(_translate("AddProgram_Window", "ADD PROGRAM"))
        self.prog_college.setText(_translate("AddProgram_Window", "College"))
        self.prog_name.setText(_translate("AddProgram_Window", "Name"))
        self.prog_code.setText(_translate("AddProgram_Window", "Code"))
        self.padd_btn.setText(_translate("AddProgram_Window", "Add"))
        self.pclear_btn.setText(_translate("AddProgram_Window", "Clear"))
        self.pcancel_btn.setText(_translate("AddProgram_Window", "Cancel"))
